function mustBeSE3Matrix(g)
    %% Validate that the input is a SE3 matrix

    % Check if matrix is real
    assert( isreal(g), ...
        "Input is not a SE3 matrix: Matrix must be real." ...
        );

    % Check size
    assert( size(g,1) == 4 && size(g,2) == 4, ...
        "Input is not a SE3 matrix: Matrix must be 4x4." ...
        );

    % Check determinant
    assert( abs(det(g) - 1 ) < 10^-10, ...
        "Input is not a SE3 matrix: Matrix must have determinant 1." ...
        );

    % Check orthogonality
    assert( all( abs((g/g) - eye(4)) < 10^-10, "all"), ...
        "Input is not a SE3 matrix: Matrix must be orthogonal." ...
        );

    % Check last row
    assert( all(g(4,:) == [0,0,0,1]), ...
        "Input is not a SE3 matrix: Last row not [0 0 0 1]." ...
        );
end