function mustBeSO3Matrix(R)
    %% Validate that the input is a SE3 matrix

    % Check if matrix is real
    assert( isreal(R), ...
        "Input is not a SO3 matrix: Matrix must be real." ...
        );

    % Check size
    assert( size(R,1) == 3 && size(R,2) == 3, ...
        "Input is not a SO3 matrix: Matrix must be 3x3." ...
        );

    % Check determinant
    assert( abs(det(R) - 1 ) < 100*eps, ...
        "Input is not a SO3 matrix: Matrix must have determinant 1." ...
        );

    % Check orthogonality
    assert( all( abs((R/R) - eye(3)) < 100*eps, "all"), ...
        "Input is not a SO3 matrix: Matrix must be orthogonal." ...
        );
end